### ISSUE TITLE
Bands are not aligned correctly

### ISSUE THREAD

**Issue by danbmd17** [sjaakp/dateline#1]
Hi! First, I'd like to say that I stumbled upon you repo while looking for something similar, ang I like it. Congrats!
In your demo, however, I have noticed that the bands do not align how I think they are supposed to.

Here, If the selected event took place in 20 October 2000, the month band should be at Oct, not Sep, The year band should be a little more to the end of 2000's and the decade band should be at the start of 2000's, right?

![event_and_bands_not_aligned](https://user-images.githubusercontent.com/23375675/61168772-ac219600-a55b-11e9-86b6-7c608e191e60.JPG)

Also, the year and month bands don't seem to be aligned:
![year_and_month_not_aligned](https://user-images.githubusercontent.com/23375675/61168773-ac219600-a55b-11e9-8a8f-b39b1df328cb.JPG)

The same with decade and year bands:
![decade_and_year_not_aligned](https://user-images.githubusercontent.com/23375675/61168774-acba2c80-a55b-11e9-91d0-97f1117381f5.JPG)

Great job, nevertheless!

**Comment by sjaakp** [comment]
Hi danbmd17,

 

Believe it or not, but on my system/browser (Windows 10, Chrome) everything looks like it should:

 



 

Nevertheless, this is an issue I should look into, of course. If only I knew where to begin! Can you tell me which system and browser you’re using?

 

Thanks!

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl <mailto:sjaak@sjaakpriester.nl> 

 

Van: danbmd17 <notifications@github.com> 
Verzonden: zaterdag 13 juli 2019 09:51
Aan: sjaakp/dateline <dateline@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [sjaakp/dateline] Bands are not aligned correctly (#1)

 

Hi! First, I'd like to say that I stumbled upon you repo while looking for something similar, ang I like it. Congrats!
In your demo, however, I have noticed that the bands do not align how I think they are supposed to.

Here, If the selected event took place in 20 October 2000, the month band should be at Oct, not Sep, The year band should be a little more to the end of 2000's and the decade band should be at the start of 2000's, right?

 <https://user-images.githubusercontent.com/23375675/61168772-ac219600-a55b-11e9-86b6-7c608e191e60.JPG> 

Also, the year and month bands don't seem to be aligned:
 <https://user-images.githubusercontent.com/23375675/61168773-ac219600-a55b-11e9-8a8f-b39b1df328cb.JPG> 

The same with decade and year bands:
 <https://user-images.githubusercontent.com/23375675/61168774-acba2c80-a55b-11e9-91d0-97f1117381f5.JPG> 

Great job, nevertheless!

**Comment by danbmd17** [comment]
Hello,

I am using the demo from here: [https://www.jqueryscript.net/demo/events-time-scales-date-line/](url)
I am also running windows 10 enterprise with chrome (Chrome 75).
My current locale is UTC+3, if that is somehow important.

Thanks

**Comment by sjaakp** [comment]
I found the problem. Resolving it took only one extra CSS-rule.

 

I just uploaded a new release (1.2.5). It will take some time, I suppose, before the change will be visible om the demo-site. But if you like to embed Dateline in your site, you can now safely do so, I think.

 

Thanks again

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl <mailto:sjaak@sjaakpriester.nl> 

 

Van: danbmd17 <notifications@github.com> 
Verzonden: maandag 15 juli 2019 11:07
Aan: sjaakp/dateline <dateline@noreply.github.com>
CC: Sjaak Priester <sjaak@sjaakpriester.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [sjaakp/dateline] Bands are not aligned correctly (#1)

 

Hello,

I am using the demo from here: https://www.jqueryscript.net/demo/events-time-scales-date-line/
I am also running windows 10 enterprise with chrome (Chrome 75).
My current locale is UTC+3, if that is somehow important.

Thanks

**Comment by danbmd17** [comment]
Wow, thank you! It seems to work now :D
