### ISSUE TITLE
Is there anyway to rebind the event and refresh dateline

### ISSUE THREAD

**Issue by gayan-rb** [sjaakp/dateline#10]
i just want to know. is there any way to rebind and refresh dateline dynamically with different values

**Comment by sjaakp** [comment]
No, sorry, there is not.

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl <mailto:sjaak@sjaakpriester.nl> 

 

Van: Gayan Ranasinghe <notifications@github.com> 
Verzonden: zondag 24 mei 2020 04:13
Aan: sjaakp/dateline <dateline@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [sjaakp/dateline] Is there anyway to rebind the event and refresh dateline (#10)

 

i just want to know. is there any way to rebind and refresh dateline dynamically with different values

**Comment by gayan-rb** [comment]
OK thanks
