### ISSUE TITLE
event `datelinechange ` always returning the current date

### ISSUE THREAD

**Issue by LorisC** [sjaakp/dateline#2]
Hello tried on differente sample and the demo site but the event is always returning the current date

**Comment by sjaakp** [comment]
Yes, I know. It’s a shame. But a new version is in the works and it will be much better!

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl <mailto:sjaak@sjaakpriester.nl> 

 

Van: Loris Ciprin <notifications@github.com> 
Verzonden: dinsdag 30 juli 2019 16:00
Aan: sjaakp/dateline <dateline@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [sjaakp/dateline] event `datelinechange ` always returning the current date (#2)

 

Hello tried on differente sample and the demo site but the event is always returning the current date
