### ISSUE TITLE
Problem with MINUTES scale

### ISSUE THREAD

**Issue by acdavidson** [sjaakp/dateline#3]
Hi,

I think a small typo has crept into Band.js.  

https://github.com/sjaakp/dateline/blob/ea24ca7caa138ce389ed4a7f3170b808674d245a/src/Band.js#L44

setMiMinute  >> setMinute ???

This appears to affect Minutes scales.

Love the widget!

**Comment by sjaakp** [comment]
Of course! Thanks!
